### ISSUE TITLE
Module Issues

### ISSUE THREAD

**Issue by BennyBoi93** [zeque92/RealTime3DwithPython#2]
I am having an issue with this program.  In the various programs, they attempt to import the "numpy" module.  Python doesn't recognize this module, and consequently, it won't work.  Furthermore, the Vector3D Part 8 calls the "scipy" module, and I run into the same issue.  I don't know if these modules come from a python extension I'm not aware of, but help would be appreciated.

**Comment by zeque92** [comment]
Many Python installations come with these modules included as standard, but if you don't have them, look at e.g. https://numpy.org/install/

Basically just using 
pip install numpy
should do it, and the same for any other modules used.
